fail_fast: true
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.8
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-added-large-files
      args: ["--maxkb=1000"]
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
      exclude: ^\.vscode/
    - id: check-toml
    - id: pretty-format-json
      args: ["--autofix"]
      exclude: ^\.vscode/
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: check-docstring-first


# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: "v1.6.0"
#   hooks:
#     - id: mypy
#       additional_dependencies: ['types-toml', 'pandas-stubs','sqlalchemy-stubs','google-auth-stubs']

#       args: [--no-strict-optional, --config-file=pyproject.toml]


# TODO: Reactivate docformatter
# after https://github.com/PyCQA/docformatter/issues/289 is fixed
# - repo: https://github.com/PyCQA/docformatter
#   rev: v1.7.5
#   hooks:
#     - id: docformatter
#       additional_dependencies: [tomli]
#       args: [--in-place]
